**Brodcasting**
Scalar broadcasting

In [1]:
import numpy as np

arr=np.arange(20)
print(arr*3)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]


In [ ]:
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6).reshape(3,2)
print(arr1)


In [ ]:
arr1*arr2

**Insert Base BroadCoast**

In [2]:
h=[1,2,3,4,5]
y=[6,7,8,9,10]
h_arr=np.array([h,y])
print(np.shape(h_arr))
print(h_arr)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
f=np.array([[6],[4]])
print(f)
np.shape(f)

[[6]
 [4]]


(2, 1)

In [5]:
h_arr*f

array([[ 6, 12, 18, 24, 30],
       [24, 28, 32, 36, 40]])

In [ ]:
x=np.array([['AZ','NZ'],['ZM','IND']])
y=np.array([['PK','AO'],['SNZ','BZ']])
print(x)
print(y)

In [6]:
print(np.concatenate((x,y)))    # By default axis=0
print(np.concatenate((x,y),axis=1))

NameError: name 'x' is not defined

In [ ]:
id=[1,2,3,4]
name=['Alex','RockY','Mark','Tom']
marks=[80,60,80,90]

id_arr=np.array(id,dtype='float')
id_name=np.array(name)
id_marks=np.array(marks)

print(id_arr)
print(id_name)
print(id_marks)

In [ ]:
n_arr=np.stack((id_arr,id_name,id_marks))
n_arr

In [ ]:
id_arr.dtype.name # Check the datatype of array

In [ ]:
n_arr.dtype.name

In [ ]:
n_arr1=np.stack((id_arr,id_name,id_marks),axis=0)
n_arr1

In [ ]:
n_arr1=np.vstack((id_arr,id_name,id_marks))
n_arr1