In [3]:
import numpy as np
arr=np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
for i in arr:
    print(i)

[0 1]
[2 3]
[4 5]


In [9]:
for i in arr:
    for j in i:
        print(j)

0
1
2
3
4
5


In [11]:
a1=np.arange(6)
for i in a1:
    print(i)

0
1
2
3
4
5


**2D Array**

In [20]:

student=np.array([
    ["Alax","Tez","Rockey"],
    [20,30,28],
    [68,78,90]
])
student.flatten()
#np.shape(student)

array(['Alax', 'Tez', 'Rockey', '20', '30', '28', '68', '78', '90'],
      dtype='<U6')

In [19]:
student.flatten(order='F')

array(['Alax', '20', '68', 'Tez', '30', '78', 'Rockey', '28', '90'],
      dtype='<U6')

In [26]:
for i in np.nditer(student,order='F'):
    print(i)

Alax
20
68
Tez
30
78
Rockey
28
90


In [27]:
for i in np.nditer(student,flags=['external_loop']):
    print(i)

['Alax' 'Tez' 'Rockey' '20' '30' '28' '68' '78' '90']


In [33]:
arr_2d=np.arange(10).reshape(5,2)
arr_2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
for i in range(len(arr_2d)):
    #print(i)
    if i==0:
        print("ODD:- ",arr_2d[i])
    elif i%2!=0:
        print("ODD:-",arr_2d[i])
    elif i%2==0:
        print("Even:-",arr_2d[i])

ODD:-  [0 1]
ODD:- [2 3]
Even:- [4 5]
ODD:- [6 7]
Even:- [8 9]


In [50]:
arr_2d[::2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [58]:
arr=np.arange(6).reshape(3,2)
print(arr)
for i in np.nditer(arr,op_flags=['readwrite']):
    i[...]=i*i #[...] for multiple data type also it will work since simple loop multiplication

print(arr)

[[0 1]
 [2 3]
 [4 5]]
[[ 0  1]
 [ 4  9]
 [16 25]]


In [62]:
arr1=np.array([[1,2,3],
              [4,5,6]])
arr2=np.array([[7,8,9],
              [10,11,12]])
arr1*arr2**2

array([[ 49, 128, 243],
       [400, 605, 864]])

In [67]:
l=['SL','IND','NZ','AUS','ENG','AF']
arr3=np.array(l).reshape(-1,2)            # we can give either correct row or col will calculate the other number autoetically. 
arr3

array([['SL', 'IND'],
       ['NZ', 'AUS'],
       ['ENG', 'AF']], dtype='<U3')

**Spliting**

In [79]:
arr=np.arange(9)
np.split(arr,3)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [85]:
arr4=np.arange(24).reshape(8,3)
np.split(arr4,4)


[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]), array([[12, 13, 14],
        [15, 16, 17]]), array([[18, 19, 20],
        [21, 22, 23]])]

In [84]:
a,b,c,d=np.split(arr4,4)
print(a)
print(b)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]]


In [98]:
arr1=np.array([['Aus','SL','AF'],
              ['NZ','IND','WI']])
np.hsplit(arr1,3)


[array([['Aus'],
        ['NZ']], dtype='<U3'), array([['SL'],
        ['IND']], dtype='<U3'), array([['AF'],
        ['WI']], dtype='<U3')]

In [100]:
np.vsplit(arr1,2)

[array([['Aus', 'SL', 'AF']], dtype='<U3'),
 array([['NZ', 'IND', 'WI']], dtype='<U3')]

In [102]:
n1=np.arange(6)
n2=n1.view()
n3=n2.view()
print(n1)
print(n2)
print(n3)


[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [106]:
print(id(n1))
print(id(n2))
print(id(n3))

2729976199168
2729968840912
2729968841072


In [120]:
print(n2 is n1)
print(n2.base is n1)
print(n3.base is n1)


False
True
True


In [113]:
n2[1]=80

In [118]:
print(n1)
print(n3)

[ 0 80  2  3  4  5]
[ 0 80  2  3  4  5]


In [124]:
n2=n1.copy()
n3=n2.copy()
n2[1]=90
n2

array([ 0, 90,  2,  3,  4,  5])