In [12]:
import numpy as np

**3D Array**

In [8]:
three_d_arr=np.arange(36).reshape(3,3,4)
print(three_d_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [9]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [10]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [16]:
np.nan

nan

In [17]:
np.set_printoptions(threshold = np.nan)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

**Converting list to Array - can have only one data Type**

arr.dim  / arr.dtype   / arr.shape   /  arr.size   / 

In [21]:
arr=np.array(object=[1,2,3],dtype='str')
arr1=np.array(object=[1,2,3],dtype='int')


In [23]:
arr1=arr1.astype('float') # Type Convertion
print(arr1.dtype)

float64
